base_url = "https://blackmagezeraf.github.io/personal-blogs"
title = "Ali Hussain Abid Blogs"
description = "A minimal, reading-friendly dark theme blog."
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true

[extra]
author = "Ali Hussain Abid"
